[build]
  command = "./update-theme.sh && pnpm build"
  publish = "dist"
  functions = "netlify/functions"
[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-schedule"

[[plugins.inputs.schedules]]
  name = "deleteOldPosts"
  schedule = "@daily"
  command = "netlify-lambda invoke deleteOldPosts"